// ==========================================================================
// Guidesoft.MCP — Real-World Agentic Zero-Code AI Platform Builder Studio Engine
// ==========================================================================

// Global State
const builderState = {
  activeFile: 'mcp-config.json',
  currentLeftTab: 'files',
  currentCanvasView: 'preview',
  currentDevice: 'desktop',
  isAgentRunning: false,
  isRecordingVoice: false,

  // Virtual Filesystem Store
  files: {
    'mcp-config.json': `{
  "version": "1.0.0",
  "name": "guidesoft-platform-stack",
  "mcpServers": {
    "postgresql": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-postgres", "postgresql://admin:secret@localhost:5432/appdb"],
      "tools": ["query", "create_table", "inspect_schema"]
    },
    "stripe": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-stripe"],
      "env": { "STRIPE_SECRET_KEY": "sk_test_..." },
      "tools": ["create_checkout_session", "get_subscriptions"]
    },
    "whatsapp": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-whatsapp"],
      "tools": ["send_text", "send_interactive_buttons"]
    }
  }
}`,
    'server.js': `// Guidesoft.MCP Autonomous Server Gateway
import { MCPClient } from '@modelcontextprotocol/sdk';
import express from 'express';

const app = express();
app.use(express.json());

const mcpClient = new MCPClient({
  routerUrl: 'http://localhost:8080'
});

// Autonomous MCP Tool Router
app.post('/api/mcp/dispatch', async (req, res) => {
  const { targetServer, toolName, arguments: args } = req.body;
  try {
    const response = await mcpClient.callTool(targetServer, toolName, args);
    res.json({ success: true, response });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.listen(3000, () => console.log('MCP Gateway listening on port 3000'));`,
    'schema.sql': `-- PostgreSQL Schema generated by Guidesoft.MCP Coder Agent
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) UNIQUE NOT NULL,
  subscription_status VARCHAR(50) DEFAULT 'inactive',
  stripe_customer_id VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mcp_agent_logs (
  id SERIAL PRIMARY KEY,
  agent_role VARCHAR(50),
  prompt_text TEXT,
  tool_invoked VARCHAR(100),
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);`,
    'docker-compose.yml': `version: '3.8'

services:
  mcp-router:
    image: guidesoft/mcp-router:latest
    ports:
      - "8080:8080"
    environment:
      - MCP_SERVERS=postgresql:5432,stripe:8001,whatsapp:8002

  app-gateway:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mcp-router
    environment:
      - NODE_ENV=production`,
    'App.tsx': `// React Preview UI generated by Guidesoft.MCP
import React, { useState } from 'react';

export default function App() {
  const [status, setStatus] = useState('Active');

  return (
    <div style={{ padding: '20px', color: '#fff' }}>
      <h2>Guidesoft MCP Zero-Code Application</h2>
      <p>Status: {status}</p>
      <button style={{ padding: '8px 16px', background: '#6366f1', color: '#fff', border: 'none', borderRadius: '6px' }}>
        Invoke Stripe MCP Subscription
      </button>
    </div>
  );
}`
  },

  // Active MCP Servers
  mcpServers: [
    { name: 'postgresql-mcp', status: 'Connected', tools: ['query', 'create_table', 'vector_search'] },
    { name: 'stripe-mcp', status: 'Connected', tools: ['create_checkout', 'billing_portal'] },
    { name: 'whatsapp-mcp', status: 'Connected', tools: ['send_message', 'webhook_listener'] },
    { name: 'resend-mcp', status: 'Connected', tools: ['send_email'] },
    { name: 'aws-lambda-mcp', status: 'Idle', tools: ['deploy_function'] }
  ]
};

// Initialize App
document.addEventListener('DOMContentLoaded', () => {
  if (window.lucide) lucide.createIcons();
  renderFileTree();
  renderMcpServerList();
  openFileInEditor('mcp-config.json');
  renderSimulatedAppView();
});

// Left Sidebar Tab Switcher
function switchLeftTab(tabName) {
  builderState.currentLeftTab = tabName;
  document.querySelectorAll('.snav-btn').forEach(btn => btn.classList.remove('active'));
  document.querySelectorAll('.stab-content').forEach(c => c.classList.remove('active'));

  const btn = document.getElementById(`stab-${tabName}`);
  const content = document.getElementById(`content-${tabName}`);
  if (btn) btn.classList.add('active');
  if (content) content.classList.add('active');
}

// Render Workspace File Tree
function renderFileTree() {
  const container = document.getElementById('file-tree-container');
  if (!container) return;

  let html = `
    <div class="tree-folder"><i data-lucide="folder"></i> <span>guidesoft-project</span></div>
  `;

  Object.keys(builderState.files).forEach(filename => {
    const isActive = filename === builderState.activeFile ? 'active' : '';
    html += `
      <div class="tree-file ${isActive}" onclick="openFileInEditor('${filename}')">
        <i data-lucide="file-code"></i>
        <span>${filename}</span>
      </div>
    `;
  });

  container.innerHTML = html;
  if (window.lucide) lucide.createIcons();
}

// Open File in Code Editor
function openFileInEditor(filename) {
  builderState.activeFile = filename;
  renderFileTree();

  const fnElem = document.getElementById('current-filename');
  if (fnElem) fnElem.innerHTML = `<i data-lucide="file-code"></i> <span>${filename}</span>`;

  const codeElem = document.getElementById('editor-code-content');
  if (codeElem) {
    codeElem.innerText = builderState.files[filename] || '// Empty File';
  }

  if (window.lucide) lucide.createIcons();
}

// Render MCP Server List
function renderMcpServerList() {
  const container = document.getElementById('mcp-server-list');
  if (!container) return;

  let html = '';
  builderState.mcpServers.forEach(srv => {
    html += `
      <div class="mcp-card-item">
        <div class="mcp-card-header">
          <span>${srv.name}</span>
          <span style="color:#10b981; font-size:0.7rem;">● ${srv.status}</span>
        </div>
        <div class="mcp-tool-tags">
          ${srv.tools.map(t => `<span class="mcp-tag">${t}</span>`).join('')}
        </div>
      </div>
    `;
  });

  container.innerHTML = html;
}

// Prompt Recipe Presets
function applyRecipe(recipeType) {
  const promptInput = document.getElementById('prompt-input');
  if (!promptInput) return;

  if (recipeType === 'saas') {
    promptInput.value = "Build a multi-tenant SaaS application with PostgreSQL customer storage, Stripe subscription checkout, and automated Resend welcome emails via MCP.";
  } else if (recipeType === 'ai-chat') {
    promptInput.value = "Create a real-time AI Agent platform backed by PostgreSQL vector embeddings and Model Context Protocol routing.";
  } else if (recipeType === 'whatsapp') {
    promptInput.value = "Assemble an autonomous WhatsApp Business bot with lead capture, AI query resolution, and live CRM sync.";
  }
}

// Voice Dictation Input Toggle
function toggleVoiceInput() {
  builderState.isRecordingVoice = !builderState.isRecordingVoice;
  const btn = document.getElementById('voice-btn');

  if (builderState.isRecordingVoice) {
    btn.style.color = '#f43f5e';
    logTerminal('Listening for voice prompt dictation...', 'info');
    setTimeout(() => {
      applyRecipe('saas');
      toggleVoiceInput();
      logTerminal('Voice prompt transcribed successfully.', 'success');
    }, 2500);
  } else {
    btn.style.color = 'inherit';
  }
}

// Canvas View Switcher (App Preview vs Graph vs Inspector)
function switchCanvasView(viewName) {
  builderState.currentCanvasView = viewName;
  document.querySelectorAll('.cmode-btn').forEach(btn => btn.classList.remove('active'));
  document.querySelectorAll('.canvas-view-pane').forEach(pane => pane.classList.remove('active'));

  const btn = document.getElementById(`cmode-${viewName}`);
  const pane = document.getElementById(`pane-${viewName}`);
  if (btn) btn.classList.add('active');
  if (pane) pane.classList.add('active');
}

// Viewport Device Frame Switcher (Desktop, Tablet, Mobile)
function setViewportDevice(device) {
  builderState.currentDevice = device;
  document.querySelectorAll('.cdevice-btn').forEach(btn => btn.classList.remove('active'));
  const btn = document.getElementById(`cdev-${device}`);
  if (btn) btn.classList.add('active');

  const canvasArea = document.getElementById('viewport-canvas-area');
  if (canvasArea) {
    canvasArea.className = `viewport-canvas-area viewport-${device}`;
  }
}

// Render Live Simulated App Viewport
function renderSimulatedAppView() {
  const frame = document.getElementById('simulated-app-frame');
  if (!frame) return;

  frame.innerHTML = `
    <div class="app-comp-card comp-hero">
      <h2>Guidesoft Agentic SaaS Dashboard</h2>
      <p>Assembled zero-code platform running 5 active MCP Server nodes.</p>
      <button class="comp-btn" onclick="triggerAppAction('checkout')">Subscribe via Stripe MCP ($29/mo)</button>
    </div>

    <div class="app-comp-card" style="background:rgba(6, 182, 212, 0.08); border-color: rgba(6, 182, 212, 0.3);">
      <h4 style="color:#06b6d4; font-size:0.85rem; margin-bottom:0.4rem;">PostgreSQL Database Status</h4>
      <p style="font-size:0.75rem; color:#94a3b8;">Connected to appdb • 2 Tables Created • 0.4ms Query Latency</p>
    </div>

    <div class="app-comp-card" style="background:rgba(16, 185, 129, 0.08); border-color: rgba(16, 185, 129, 0.3);">
      <h4 style="color:#10b981; font-size:0.85rem; margin-bottom:0.4rem;">WhatsApp AI Bot Node</h4>
      <p style="font-size:0.75rem; color:#94a3b8;">Webhook active on port 8002 • Auto-responder ready</p>
    </div>
  `;
}

function triggerAppAction(actionType) {
  if (actionType === 'checkout') {
    logTerminal('[MCP-STRIPE] Invoking `create_checkout_session` tool call...', 'info');
    setTimeout(() => {
      logTerminal('[MCP-STRIPE] Checkout session created: https://checkout.stripe.com/c/pay/cs_test_a1b2c3', 'success');
      alert('Stripe MCP Checkout Session Created Successfully!');
    }, 800);
  }
}

// Autonomous Agentic Execution Loop
function startAgenticWorkflow() {
  const promptInput = document.getElementById('prompt-input');
  const userPrompt = promptInput ? promptInput.value.trim() : '';

  if (!userPrompt) {
    alert('Please enter a software specification prompt or select a recipe!');
    return;
  }

  logTerminal(`🚀 Starting Autonomous Agentic Workflow...`, 'agent');
  logTerminal(`[PROMPT] "${userPrompt}"`, 'info');

  const steps = [
    { delay: 600, text: '[Architect Agent] Parsing specification & selecting MCP server topology...', type: 'agent' },
    { delay: 1300, text: '[MCP Router] Bound PostgreSQL, Stripe, and Resend protocol schemas.', type: 'info' },
    { delay: 2000, text: '[Coder Agent] Generating database DDL (`schema.sql`) and server endpoints (`server.js`)...', type: 'agent' },
    { delay: 2700, text: '[UI Synthesizer] Compiling React frontend preview components...', type: 'info' },
    { delay: 3400, text: '[DevOps Agent] Building `docker-compose.yml` multi-container stack...', type: 'agent' },
    { delay: 4100, text: '✅ AGENT WORKFLOW COMPLETE! Platform software generated & validated.', type: 'success' }
  ];

  steps.forEach(step => {
    setTimeout(() => {
      logTerminal(step.text, step.type);
      if (step.type === 'success') {
        openFileInEditor('server.js');
        switchCanvasView('preview');
      }
    }, step.delay);
  });
}

// MCP Inspector Execution Simulation
function runInspectorToolCall() {
  const srvSelect = document.getElementById('inspector-mcp-select');
  const toolSelect = document.getElementById('inspector-tool-select');
  const jsonOut = document.getElementById('inspector-json-output');

  const srv = srvSelect ? srvSelect.value : 'postgres';
  const tool = toolSelect ? toolSelect.value : 'query';

  logTerminal(`[MCP-INSPECTOR] Executing tool call \`${tool}\` on server \`${srv}\`...`, 'info');

  if (jsonOut) {
    jsonOut.innerText = `{\n  "jsonrpc": "2.0",\n  "result": {\n    "status": "success",\n    "server": "${srv}",\n    "tool_executed": "${tool}",\n    "data": [\n      { "id": "usr_99", "status": "active", "created_at": "${new Date().toISOString()}" }\n    ]\n  },\n  "id": ${Math.floor(Math.random() * 9000) + 1000}\n}`;
  }

  logTerminal(`[MCP-INSPECTOR] Tool call returned 200 OK (latency 12ms).`, 'success');
}

// Log Terminal Utility
function logTerminal(message, type = 'info') {
  const body = document.getElementById('terminal-body');
  if (!body) return;

  const now = new Date();
  const timeStr = `${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;

  const entry = document.createElement('div');
  entry.className = `log-entry ${type}`;
  entry.innerText = `[${timeStr}] ${message}`;

  body.appendChild(entry);
  body.scrollTop = body.scrollHeight;
}

function clearTerminalLogs() {
  const body = document.getElementById('terminal-body');
  if (body) body.innerHTML = '';
}

// MCP Catalog Modal
function openMcpCatalogModal() {
  document.getElementById('mcp-modal').classList.add('active');
}

function closeMcpCatalogModal() {
  document.getElementById('mcp-modal').classList.remove('active');
}

function addMcpServer(serverName) {
  builderState.mcpServers.push({
    name: `${serverName.toLowerCase().replace(/\s+/g, '-')}-mcp`,
    status: 'Connected',
    tools: ['execute', 'configure']
  });
  renderMcpServerList();
  closeMcpCatalogModal();
  logTerminal(`[MCP-MARKETPLACE] Attached new MCP server: ${serverName}`, 'success');
}

// Diagnostic Health Check
function runHealthCheck() {
  logTerminal('--- RUNNING MCP DIAGNOSTICS ---', 'info');
  logTerminal('✔ MCP JSON-RPC Protocol Bus: HEALTHY', 'success');
  logTerminal('✔ Local Docker Socket: ACTIVE', 'success');
  logTerminal('✔ Agent LLM Engine: ONLINE', 'success');
}

// Export Project Zip / Codebase
function exportProjectZip() {
  logTerminal('📦 Packaging Guidesoft.MCP Zero-Code Stack (Zip)...', 'info');
  setTimeout(() => {
    alert('Project Stack exported successfully! Files include mcp-config.json, server.js, schema.sql, docker-compose.yml, App.tsx.');
    logTerminal('✅ Software stack downloaded to workspace.', 'success');
  }, 600);
}

function copyCurrentCode() {
  const codeElem = document.getElementById('editor-code-content');
  if (codeElem) {
    navigator.clipboard.writeText(codeElem.innerText).then(() => {
      alert(`Copied ${builderState.activeFile} to clipboard!`);
    });
  }
}
